### PR TITLE
Increase symbol length to 12

### PR DESCRIPTION
**Pull request by bakkerthehacker**
MetaMask supports longer symbols, this adds more length to the symbols to match

### CODE REVIEW

**Comment by vittominacori** [comment]
The EIP, and the MetaMask doc too, say `A ticker symbol or shorthand, up to 5 alphanumerical characters`.

https://github.com/ethereum/EIPs/blob/master/EIPS/eip-747.md#parameters

https://docs.metamask.io/guide/registering-your-token.html#code-free-example

**Comment by bakkerthehacker** [comment]
While the docs might say 5, in practice the limit is 12 in the extension code https://github.com/MetaMask/metamask-extension/issues/7668 .  Adding custom tokens directly in metamask shows more than 5 for me.  Would be nice to not have to choose between custom icon and >5 char symbols for custom and get both.

**Comment by vittominacori** [comment]
As MetaMask gives an error for tokens longer than 6 char, I changed it to 6.

Check their code https://github.com/MetaMask/metamask-extension/blob/v9.2.0/app/scripts/controllers/preferences.js#L796

Using 12 MetaMask returns an error

image

**Comment by bakkerthehacker** [comment]
Interesting, I guess importing from a site has different restrictions in MetaMask compared to importing it directly.  There is also a request for increasing MetaMasks's internal limit past 12 https://github.com/MetaMask/metamask-extension/issues/9243 so maybe MetaMask will adjust this import restriction as well, I could try PRing MetaMask to also this 6 char restriction updated to match 12.  The other option would be to just edit the right number of chars into MetaMasks's extension storage.  

Thanks for bumping this bit anyways.

**Comment by bakkerthehacker** [comment]
The restriction on RPC symbol length has been increased to 11: https://github.com/MetaMask/metamask-extension/pull/10670

Could this PR be reopened to have the length also adjusted?  I'm not sure how often MetaMask publishes releases or how long it will take much of the user base will install the update.

**Comment by vittominacori** [comment]
Yes will update and notify you soon.

**Comment by vittominacori** [comment]
Just pushed, waiting for MetaMask to release new version.

**Comment by NickSdot** [comment]
> The restriction on RPC symbol length has been increased to 11: [MetaMask/metamask-extension#10670](https://github.com/MetaMask/metamask-extension/pull/10670)
> 
> Could this PR be reopened to have the length also adjusted? I'm not sure how often MetaMask publishes releases or how long it will take much of the user base to install the update.

I just found the first token with a length of 12: SafeFairMoon.

Because there is the limit, I can not properly add it to my MetaMask.

**Comment by vittominacori** [comment]
Limit is still 11 on MetaMask so I cannot increase. You will have an error.

Check their repo [app/scripts/controllers/preferences.js#L828](https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/controllers/preferences.js#L828)

**Pull request closed without merging**
